apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy-svc
spec:
  ports:
  - name: "reverse"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverseproxy
  type: LoadBalancer
